name: Deploy to Glitch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Glitch
      run: |
        git config --global user.email "dniskav@gmail.com"
        git config --global user.name "dniskav"
        git remote add glitch ${{ secrets.GLITCH_GIT_URL }}
        git push glitch master --force

