name: Deploy to Glitch

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Glitch
      run: |
        git config --global user.email "dniskav@gmail.com"
        git config --global user.name "dniskav"
        git remote add glitch ${{ secrets.GLITCH_GIT_URL }}
        git push glitch master --force
