name: Deploy to Glitch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Glitch
      uses: wei/git-sync@v3
      with:
        source_repo: https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        source_branch: master
        destination_repo: ${{ secrets.GLITCH_GIT_URL }}
        destination_branch: master

